NAME := miniRT
CC := cc

SRCS_DIR := src
OUT_DIR := build

SOURCES := ${wildcard ${SRCS_DIR}/*.c} ${wildcard ${SRCS_DIR}/**/*.c}

BUILD_DIR := build

ifndef PROFILE
	PROFILE=debug
endif


PROFILES := opt debug debug_mem debug_mem_sanitize debug_mem_sanitize_mem
CFLAGS := -fPIE -MMD -fPIE -Wall -Wextra -Wmaybe-uninitialized -Wmissing-field-initializers --std=c99 -pedantic -g3 $(FLAGS)

ifdef BONUS
	BUILD_NAME := ${PROFILE}_BONUS
	CFLAGS += -DBONUS
endif
ifndef BONUS
	BUILD_NAME := ${PROFILE}
endif

TAG_FILE := $(BUILD_DIR)/profile_$(BUILD_NAME)
NAME_PROFILE := $(BUILD_DIR)/$(BUILD_NAME)_$(NAME)

# TODO: Add this before entering the project
# CFLAGS += -Werror

LIBFT_DIR := ./src/libft
LIBFT := ${LIBFT_DIR}/build/$(PROFILE)_libft.a


MLX_DIR := ./src/MLX42/build
MLX_INCLUDE := ./src/MLX42/include
LIBMLX := ${MLX_DIR}/libmlx42.a

LIBS := -lm -L ${LIBFT_DIR} -lft 

UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Linux)
	LIBS += -L${MLX_DIR} -lmlx42 -lglfw
	CFLAGS += -I ${MLX_INCLUDE}
endif
ifeq ($(UNAME_S),Darwin)
	LIBS += -L${MLX_DIR} -lmlx42 -lglfw
	CFLAGS += -I ${MLX_INCLUDE}
endif

ifeq ($(PROFILE),opt)
	CFLAGS += -O3 -flto
endif

ifeq ($(PROFILE),debug)
	CFLAGS += -Og
endif

ifeq ($(PROFILE),debug_mem)
	CFLAGS += -DDEBUG_ALLOC
endif

ifeq ($(PROFILE),debug_mem_sanitize)
	ifeq ($(UNAME_S),Darwin)
		CFLAGS += -DDEBUG_ALLOC -fsanitize=address,undefined
	else
		CFLAGS += -DDEBUG_ALLOC -fsanitize=address,leak,undefined
	endif
endif
ifeq ($(PROFILE),debug_mem_sanitize_mem)
	ifeq ($(UNAME_S),Darwin)
		CFLAGS += -DDEBUG_ALLOC -fsanitize-recover=all -fsanitize=undefined,memory -fsanitize-memory-track-origins -fPIE -fno-omit-frame-pointer
	else
		CFLAGS += -DDEBUG_ALLOC -fsanitize-recover=all -fsanitize=undefined,memory -fsanitize-memory-track-origins -fPIE -fno-omit-frame-pointer
	endif
endif

PROFILE_FOUND := $(filter $(PROFILE), $(PROFILES))

OBJS := $(SOURCES:%.c=$(BUILD_DIR)/$(BUILD_NAME)/%.o)

define NL


endef

$(if ${PROFILE_FOUND}, , $(error Unknown profile" ${PROFILE}${NL}Choose one of: $(PROFILES)))

all: $(NAME)

bonus: $(NAME)

$(NAME): $(NAME_PROFILE) ${TAG_FILE}
	cp $(NAME_PROFILE) $(NAME)

# It's important that libft get's made first, because if it's not,
# the autogenerated header files might be missing as dependencies
$(NAME_PROFILE):: $(LIBFT)
$(NAME_PROFILE):: $(LIBFT) $(LIBMLX) $(OBJS)
	${CC} ${CFLAGS} -o $(NAME_PROFILE) $(OBJS) $(LIBS) 

${TAG_FILE}:
	mkdir -p build
	rm -rf $(BUILD_DIR)/profile_*
	touch ${TAG_FILE}

$(LIBFT): FORCE
	CC=${CC} $(MAKE) -j -C ${LIBFT_DIR}

$(LIBMLX):
	mkdir -p ${MLX_DIR}
	cd ${MLX_DIR} && cmake .. -G "Unix Makefiles"
	$(MAKE) -C ${MLX_DIR} -j

FORCE: ;

build/${BUILD_NAME}/%.o: %.c Makefile
	@mkdir -p $$(dirname $@)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(BUILD_DIR)
	$(MAKE) -C $(LIBFT_DIR) fclean
	rm -rf ${MLX_Dir}

fclean: clean
	rm -rf $(NAME)

re::fclean
re::all

.PHONY: clean fclean re all
-include $(SOURCES:%.c=$(BUILD_DIR)/$(PROFILE)/%.d)
